#!/bin/bash
#SBATCH -J compr
#SBATCH -N 1           # nodes number (=NBP)   
#SBATCH -n 1           # CPUs number (on all nodes) (=NBP*TPN) 
#SBATCH -o MNH06.eo%j   #
#SBATCH -e MNH06.eo%j   #
#SBATCH -t 10:00:00    # time limit


module load intel
module load netcdf-c
module load nco
module load udunits


python compressor.py
